# 使用figaro这个gem在此添加配置ENV的参数
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#

 DATABASE_PASSWORD: xxxx

 production:
   DATABASE_PASSWORD: xxxx
   REDIS_PASSWORD: xxxx
   SIDEKIQ_USRRNAME: xxxx
   SIDEKIQ_PASSWORD: xxxx

