base: &base
  adapter: mysql2
  host: localhost
  encoding: utf8
  reconnect: ture
  timeout: 1000
  pool: 5
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *base
  database: blog_dev


production:
  <<: *base
  database: blog

test:
  <<: *base
  database: blog_test