base: &base
  adapter: mysql2
  host: localhost
  encoding: utf8
  reconnect: ture
  timeout: 1000
  pool: 5
  username: root
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database_password] %>

development:
  <<: *base
  database: init_gems_dev


production:
  <<: *base
  database: init_gems

test:
  <<: *base
  database: init_gems_test