base: &base
  timeout: 2

development: &development
  <<: *base
  port: 6379
  password:

production:
  <<: *base
  port: 6378
  password: <%= ENV["REDIS_PASSWORD"] %>

sidekiq:
  <<: *base
  port: 6378
  password: <%= ENV["REDIS_PASSWORD"] %>
  db: 1
  namespace: highlander_sidekiq

local_sidekiq:
  <<: *base
  port: 6379
  password:
  db: 1
  namespace: highlander_sidekiq