base: &base
  host: 127.0.0.1
  timeout: 2

development:
  <<: *base
  port: 6379
  password:

test:
  <<: *base
  port: 6379
  password:

production:
  <<: *base
  port: 6379
  password: <%= Rails.application.credentials[Rails.env.to_sym][:redis_password].to_s %>