# 默认为 redis://localhost:6379/0
# 确保是完整的redis地址，可以设置远程地址
redis_url: "redis://localhost:6379/3"
# 默认为空, 建议使用hiredis(并确保有这个gem)
redis_driver: :hiredis
# 记录每天的最慢的请求数存储量，默认500
slow_actions_limit:
# 记录每天的每个Action最慢的N个请求，默认20
action_slow_request_limit:
# 项目名，默认为 'app'，区分项目名可以多个项目数据存于一台redis server上
app_name: 'Blog'
# 记录SQL的最低时间（单位：秒），小于指定数值的则不记录
sql_critical_time: 0.1
# 不统计的请求(值为：xxxController#Action)（数组）
#  - Devise::SessionsController#create
exclude_actions:
